name: Mean Stats

on:
  push: 
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    
    - name: Cache packages  
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
    - name: Install
      run: yarn install && yarn build
      
    - name: Update Files
      uses: test-room-7/action-update-file@v1
      with:
          file-path: '*.js'
          commit-msg: Update JS files
          github-token: ${{ secrets.GITHUB_TOKEN }}